<a href="https://colab.research.google.com/github/sooonsyk/ESAA-22-2/blob/main/W6_HW_fri.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**텍스트 분석**
- NLP(National Language Processing) : 머신이 인간의 언어를 이해하고 해석하는 데 중점
  - 텍스트 분석을 향상하게 하는 기반 기술
- 텍스트 분석(Text analytics, Text Mining) : 비정형 텍스트에서 의미 있는 정보를 추출하는 것에 더 중점
  - 머신러닝, 언어 이해, 통계 등을 활용해 모델을 수립하고 정보를 추출해 비즈니스 인텔리전스나 예측 분석 등의 분석 작업 주로 수행
  - 텍스트 분류 Text classification : text categorization 문서가 특정 분류 또는 카테고리에 속하는 것을 예측하는 기법, 지도학습 적용
  - 감성 분석 Sentiment analysis : 텍스트에서 나타나는 주관적인 요소를 분석하는 기법 총칭
  - 텍스트 요약 summarization : 텍스트 내에서 중요한 주제나 중심 사상을 추출하는 기법
  - 텍스트 군집화와 유사도 측정 : 비슷한 유형의 문서에 대해 군집화 수행하는 기법, 텍스트 분류를 비지도 학습으로 수행하는 방법의 일환으로 사용, 유사도 측정 역시 문서들간의 유사도 측정해 비슷한 문서끼리

  

##1. 텍스트 분석 이해
- 비정형 데이터인 텍스트를 분석하는 것
- 머신러닝 알고리즘은 숫자형의 피처 기반 데이터만 입력받을 수 있기 때문에 텍스트를 머신러닝에 적용하기 위해서는 비정형 텍스트 데이터를 어떻게 피처 형태로 추출하고 추출된 피처에 의미 있는 값을 부여하는가가 매우 중요
  - 피처 벡터화 feature vectorization/ 피처 추출 feature extraction : 텍스트를 word 기반의 다수의 피처로 추출하고 이 피처에 단어 빈도수와 같은 숫자 값을 부여하면 텍스트는 단어의 조합인 벡터값으로 변환할 수 있음 - BOW bag of words 방식 사용
- 텍스트 분석 수행 프로세스
  1. 텍스트 사전 준비작업(텍스트 전처리) : 텍스트를 피처로 만들기 전에 미리 클렌징, 대/소문자 변경, 특수문자 삭제 등의 클렌징 작업, 단어 등의 토큰화 작업, 의미 없는 단어 stop word 제거 작업, 어근 추출 stemming/lemmatization 등의 텍스트 정규화 작업 수행 통칭
  2. 피처 벡터화/추출 : 사전 준비 작업으로 가공된 텍스트에서 피처를 추출하고 여기에 벡터값 할당
  3. ML 모델 수립 및 학습/예측/평가 : 피처 벡터화된 데이터 세트에 ML 모델을 적용해 학습/예측/ 및 평가 수행
- 파이썬 기반의 NLP, 텍스트 분석 패키지
  - NTLK Natural language toolkit for python : 파이썬의 가장 대표적인 NLP 패키지, 방대한 데이터 세트와 서브 모듈을 가지고 있으며 NLP의 거의 모든 영역을 커버하고 있음, 많은 NLP 패키지가 NTLK의 영향을 받아 작성되고 잇음, 수행 속도가 아쉬워서 실제 대량의 데이터 기반에서는 제대로 활용되지 못 함
  - Gensim : 토픽 모델링 분야에서 가장 두각을 나타냄, 오래전부터 토픽 모델링을 쉽게 구혀할 수 있는 기능을 제공해왔으며 Word2Vec 구현 등의 다양한 신기능 제공, SpaCy와 함께 가장 많이 쓰임
  - SpaCy : 뛰어난 수행 성능으로 가장 주목,
- 사이킷런은 머신러닝 위주의 라이브러리여서 NLP를 위한 다양한 라이브러리, NLP 패키지에 특화된 라이브러리 가지고 있지 않음, 하지만 텍스트를 일정 수준으로 가공하고 머신러닝 알고리즘에 텍스트 데이터를 피처로 처리하기 위한 편리한 기능 제공하고 있어 사이킷런으로도 텍스트 분석 기능 수행 가능

##2. 텍스트 사전 준비 작업(텍스트 전처리) - 텍스트 정규화
- 텍스트 자체를 바로 피처로 만들 수 없음 - 가공하는 준비 작업 필요
- **클렌징** : 텍스트에서 분석에 오히려 방해가 되는 불필요한 문자, 기호 등을 사전에 제거
- **텍스트 토큰화** : 문서에서 문장을 분리하는 문장 토큰화와 문장에서 단어를 토큰으로 분리하는 단어 토큰화
  - 문장 토큰화 : 문장의 마침표, 개행문자 등 문장의 마지막을 뜻하는 기호에 따라 분리하는 것이 일반적, 정규 표현식에 따른 문장 토큰화도 가능
  - 단어 토큰화 : 문장을 단어로 토큰화, 공백 컴마 마침표 개행문자 등으로 단어를 문리하지만 정규 표현식을 이용해 다양한 유형으로 토큰화 수행할 수 있음
      - 문장을 분리하는 구분자를 이용해 단어를 토큰화할 수 있으므로 Bag of Word와 같이 단어의 순서가 중요하지 않은 경우 단어 토큰화만 사용해도 충분
      - 일반적으로 문장 토큰화 는 각 문장이 가지는 시맨틱적인 의미가 중요한 요소로 사용될 때 사용

In [19]:
#3개의 문장으로 이루어진 텍스트 문서를 문장으로 각각 분리

from nltk import sent_tokenize
import nltk
nltk.download('punkt')
# NLTK의 경우 단어 사전과 같이 참조가 필요한 데이터 세트의 경우 인터넷으로 다운 받을 수 있음, 최초 다운로드만 필요
# punkt 는 마침표 개행 문자등의 데이터 세트 다운로드

text_sample = 'The Matrix is everywhere its all around us, here even in this room. \
              You can see it out your window or on your television. \
              You feel it when you go to work, or go to church or pay your taxes'
sentences = sent_tokenize(text=text_sample)
print(type(sentences), len(sentences))
print(sentences)

<class 'list'> 3
['The Matrix is everywhere its all around us, here even in this room.', 'You can see it out your window or on your television.', 'You feel it when you go to work, or go to church or pay your taxes']


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


      - sent_tokenize()가 반환하는 것은 각각의 문장으로 구성된 list 객체

In [20]:
# 단어 토큰화

from nltk import word_tokenize

sentence = 'The Matrix is everywhere its all around us, here even in this room.'
words = word_tokenize(sentence)
print(type(words), len(words))
print(words)

<class 'list'> 15
['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.']


In [21]:
#조합해서 문서에 대해서 모든 단어 토큰화

#여러 개의 문장으로 된 입력 데이터를 문장별로 단어 토큰화하게 만드는 함수 생성
def tokenize_text(text):
  #문장별로 분리
  sentences = sent_tokenize(text)
  #분리된 문장별 단어 토큰화
  word_tokens = [word_tokenize(sentence) for sentence in sentences]
  return word_tokens

#여러 문장에 대해 문장별 단어 토큰화 수행
word_tokens = tokenize_text(text_sample)
print(type(word_tokens), len(word_tokens))
print(word_tokens)

<class 'list'> 3
[['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.'], ['You', 'can', 'see', 'it', 'out', 'your', 'window', 'or', 'on', 'your', 'television', '.'], ['You', 'feel', 'it', 'when', 'you', 'go', 'to', 'work', ',', 'or', 'go', 'to', 'church', 'or', 'pay', 'your', 'taxes']]


  - 문장을 단어별로 하나씩 토큰화할 경우 문맥적인 의미는 무시될 수밖에 없음 - n-gram 도입
  - n-gram : 연속된 n개의 단어를 하나의 토큰화 단위로 분리해 내는 것
    - n개 단어 크기 윈도우를 만들어 문장의 처음부터 오른쪽으로 움직이면서 토큰화 수행

  - **스톱 워드 제거** : 스톱워드는 분석에 큰 의미가 없는 단어, 가령 영어에서 is, the, a, will 등 문장을 구성하는 필수 문법 요소지만 문맥적으로 큰 의미가 없는 단어가 이에 해당, 문법적인 특성으로 인해 빈번하게 나타나므로 오히려 중요한 단어로 인지될 수 있으므로 제거해야 함
    - 언어별로 목록화 돼있음

In [22]:
nltk.download('stopwords')

print('영어 stop words 개수 : ', len(nltk.corpus.stopwords.words('english')))
print(nltk.corpus.stopwords.words('english')[:20])

영어 stop words 개수 :  179
['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his']


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [23]:
#word_tokens 리스트에 대해서 stopwords 필터링으로 제거 

stopwords = nltk.corpus.stopwords.words('english')
all_tokens = []

for sentence in word_tokens :
  filtered_words = []

  for word in sentence:
    word = word.lower() #소문자로 변환
    if word not in stopwords:
      filtered_words.append(word)
  all_tokens.append(filtered_words)

print(all_tokens)

[['matrix', 'everywhere', 'around', 'us', ',', 'even', 'room', '.'], ['see', 'window', 'television', '.'], ['feel', 'go', 'work', ',', 'go', 'church', 'pay', 'taxes']]


  - **Stemming 과 Lemmatization** : 문법적 또는 의미적으로 변화하는 단어의 원형을 찾는 것
    - lemmatization 이 stemming 보다 정교, 의미론적인 기반에서 단어의 원형 찾음
    - stemming은 원형 단어로 변환 시 일반적인 방법을 적용하거나 더 단순화된 방법을 적용해 원래 단어에서 일부 철자가 훼손된 어ㅓ근 단어를 추출하는 경향 있음
    - lemmatization 은 품사와 같은 문법적인 요소와 더 의미적인 부분을 감안해 정확한 철자로 된 어근 찾아줌, 더 오랜 시간 필요
    - NLTK는 porter, lancaster, snowball stemmerrhk rkxdms 다양한 stemmer 제공, lemmatization을 위해서는 WordNetLemmatizer 제공함

In [24]:
#LancasterStemmer - 진행형, 3인칭 단수, 과거형에 따른 동사. 비교, 최상에 따른 형용사의 변화에 따라 더 단순하게 원형 단어 찾아줌

from nltk.stem import LancasterStemmer
stemmer = LancasterStemmer()

print(stemmer.stem('working'), stemmer.stem('works'), stemmer.stem('worked'))
print(stemmer.stem('amusing'), stemmer.stem('amuses'), stemmer.stem('amused'))
print(stemmer.stem('happier'), stemmer.stem('happiest'))
print(stemmer.stem('fancier'), stemmer.stem('fanciest'))

work work work
amus amus amus
happy happiest
fant fanciest


In [25]:
#WordNetLemmatizer - 일반적으로 Lemmatization은 보다 정확한 원형 단어 추출을 위해 단어의 품사 입력해줘야 함, 동사 v 형용사 a

from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
nltk.download('omw-1.4') #안 하면 오류뜸

lemma = WordNetLemmatizer()
print(lemma.lemmatize('amusing','v'), lemma.lemmatize('amuses','v'), lemma.lemmatize('amused','v'))
print(lemma.lemmatize('happier','a'), lemma.lemmatize('happiest','a'))
print(lemma.lemmatize('fancier','a'), lemma.lemmatize('fanciest','a'))

amuse amuse amuse
happy happy
fancy fancy


[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


##3.Bag of Words - BOW
- 문서가 가지는 모든 단어를 문맥이나 순서를 무시하고 일괄적으로 단어에 대해 빈도 값을 부여해 피처 값을 추출하는 모델
- 쉽고 빠름, 단순히 단어의 발생 횟수에 기반하고 있지만 예상보다 문서의 특징 잘 나타냄
- 문맥 의미 반영 부족 : 단어의 순서 고려하지 않기 때문에 문장 내에서 단어의 문맥적인 의미 무시됨, n-gram 사용하더라도 제한적인 부분의 그침
- 희소행렬문제 : 피처 벡터화를 수행하면 희소 행렬 형태의 데이터 세트가 만들어지기 쉬움, 희소 행렬은 일반적으로 ML 알고리즘의 수행 시간과 예측 성능을 떨어뜨림

###BOW 피처 벡터화
- 피처 벡터화는 기존 텍스트 데이터를 또 다른 형태의 피처의 조합으로 변경하기 때문에 넓은 범위의 피처 추출에 포함함
-  모든 문서에서 단어를 칼럼 형태로 나열하고 각 문서에서 해당 단어의 횟수나 정규화된 빈도를 값으로 부여하는 데이터 세트 모델로 변경하는 것
- 카운트 백터화 : 단어 피처에 값을 부여할 때 각 문서에서 해당 단어가 나타나는 횟수를 부여하는 경우, 값이 높을수록 중요한 단어로 인식됨
  - 문서의 특징을 나타내기 보다는 언어의 특성상 문장에서 자주 사용될 수밖에 없는 단어까지 높은 값 부여
- TF-IDF (Term frequency - inverse document frequency) : 개별 문서에서 자주 나타나는 단어에 높은 가중치를 주되, 모든 문서에서 전반적으로 자주 나타나는 단어에 대해서는 페널티를 주는 방식을 값 부여
  - 문서마다 텍스트가 길고 문서의 개수가 많은 경우 카운트 방식보다 더 좋은 예측 성능 보장

###사이킷런의 Count 및 TF-IDF 구현 : CountVectorizer, TfidfVectorizer
- CountVectorizer : 단지 피처 벡터화만 수행하지는 않고 소문자 일괄 변환, 토큰화, 스톱 위드 필터링 등의 텍스트 전처리도 함께 수행
  - 텍스트 전처리 및 피처 벡터화를 위한 입력 파라미터를 설정해 동작
  - fit()과 transform()을 통해 피처 벡터화된 객치 반환함
  1. 영어의 경우 모든 문자를 소문자를 변경하는 등의 전처리 작업 진행
  2. 디폴트로 단어기준으로 n_gram_range를 반영해 각 단어 토큰화
  3. 텍스트 정규화 수행
    - 단, stop_words 주저진 경우 스톱워드 필터링(영어만 가능)만 가능
    - 어근 변환은 직접 지원하지 않으나 tokenizer 파라미터에 커스텀 어근 변환 함수를 적용하여 수행할 수 있음
- TfidVectorizor

###BOW 벡터화를 위한 희소 행렬
- BOW 형태를 가진 언어 모델의 피처 벡터화는 대부분 희소 행렬
- 물리적으로 적은 메모리 공간을 차지할 수 잇도록 변환해야 함 - COO 형식, CSR 형식 활용
- 파이썬은 희소 행렬 변환을 위해 주로 scipy 활용
###희소행렬 - COO 형식
- coordinate 형식은 0 이 아닌 데이터만 별도의 데이터 배열에 저장하고 그 데이터가 가리키는 행과 열의 위치를 별도의 배열로 저장하는 방식


In [26]:
import numpy as np

dense = np.array([[3,0,1],[0,2,0]])

In [27]:
from scipy import sparse

#0이 아닌 데이터 추출
data = np.array([3,1,2])

#행 위치와 열 위치를 각각 배열로 생성
row_pos = np.array([0,0,1])
col_pos = np.array([0,2,1])

#sparse 패키지의 coo_matrix를 이용해 COO 형식으로 희소 행렬 생성
sparse_coo = sparse.coo_matrix((data, (row_pos, col_pos))) #COO 형식 희소 행렬 객체 변수

In [28]:
sparse_coo.toarray() #다시 밀집 형태의 행렬로 출력

array([[3, 0, 1],
       [0, 2, 0]])

###희소행렬 - CSR 형식
  - COO 형식이 행과 열의 위치를 나타내기 위해서 반복적인 위치 데이터를 사용해야 하는 문제점 해결한 방식
  - 행위치배열이 순차적인 값들의 반복적인 형태임을 활용해서 고유한 값의 시작 위치만 표시하는 방법으로 반복 제거, 그리고 마지막에 총 항목 개수 배열에 추가함

In [31]:
from scipy import sparse

dense2 = np.array([[0,0,1,0,0,5],
                   [1,4,0,3,2,5],
                   [0,6,0,3,0,0],
                   [2,0,0,0,0,0],
                   [0,0,0,7,0,8],
                   [1,0,0,0,0,0]])

#0이 아닌 데이터 추출
data2 = np.array([1,5,1,4,3,2,5,6,3,2,7,8,1])

#행 위치와 열 위치 각각 array로 생성
row_pos = np.array([0,0,1,1,1,1,1,2,2,3,4,4,5])
col_pos = np.array([2,5,0,1,3,4,5,1,3,0,3,5,0])

#COO방식으로 변환
sparse_coo = sparse.coo_matrix((data2, (row_pos, col_pos)))

#행 위치 배열의 고유한 값의 시작 위치 인덱스를 배열로 생성
row_pos_ind = np.array([0,2,7,9,10,12,13])

#CSR 형식으로 변환
sparse_csr = sparse.csr_matrix((data2,col_pos, row_pos_ind))

print('COO 변환된 데이터가 제대로 되었는지 다시 dense로 출력 확인')
print(sparse_coo.toarray())
print('CSR 변환된 데이터가 제대로 되었는지 다시 dense로 출력 확인')
print(sparse_csr.toarray())

COO 변환된 데이터가 제대로 되었는지 다시 dense로 출력 확인
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]
CSR 변환된 데이터가 제대로 되었는지 다시 dense로 출력 확인
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]


In [32]:
#실제 사용시 밀집 행렬을 생성 파라미터로 입력하면 희소행렬로 생성함
dense3 = np.array([[0,0,1,0,0,5],
                   [1,4,0,3,2,5],
                   [0,6,0,3,0,0],
                   [2,0,0,0,0,0],
                   [0,0,0,7,0,8],
                   [1,0,0,0,0,0]])

coo = sparse.coo_matrix(dense3)
csr = sparse.csr_matrix(dense3)

- 사이킷런의 CountVectorizer 나 TfidfVectorizer 클래스로 변환된 피처 벡터화 행렬은 모두 사이파이의 CSR 형태의 희소 행렬